### PR TITLE
Lineage 15.0

### PR DESCRIPTION
**Pull request by 1song**

### CODE REVIEW

**Comment by chautruongthinh** [comment]
I'm testing new branch!! I will merge them after i tested

**Comment by 1song** [comment]
Thanks! 
Opend the your kernel source

**Comment by chautruongthinh** [comment]
I hope you can join us to dev for Vega Iron2!! If you want please give me you Facebook nick, i will add you with my team

**Comment by 1song** [comment]
Hi chautruongthinh

I tested the los-15 source you published.
I modified several sources so that the build of rom succeeded, but
unfortunately the boot failed, whether it was a kernel problem or not.
Attach some sources that might help.

I hope you will always be lucky.

2017-12-17 17:24 GMT+09:00 chautruongthinh <notifications@github.com>:

**Comment by chautruongthinh** [comment]
My kernel booted with AOSP 8.1, but i dont know why it can not boot with Lineage-15.0.
I'm waiting Lineage-15.1 source, i hope my kernel can work with lineage-15.1

**Pull request closed without merging**
